services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./back-end
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      MONGO_URI: ${MONGO_URI}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: http://localhost:5173
    depends_on:
      - mongo

  frontend:
    build: ./front-end
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mongo_data: